apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: acr-secret
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgAcILpGGw2oyCNaNLgMZb52r4Y3PK/F+PMe8J1e3JrJa7l36Kk7MFa3nhs16lgUp6f5bGynSgQ1a5Q9q//ggkRNX+PCbTDuo5G+IomaJaQhlgcYVeWCWZDBfUIrXgUt1S5Vbvpa0esayENVX/pdynQrjd0LP9B0ftb+MuFtKSW3qVAAsspvyy2qJiaGbOpRro6EZXO3XUWilfxXIWNM5dr/KDRk648bbU+OlDhTX2bjUrbWwzfjpquf34x/rWht7EerBxDT9I4huZWRClKA5M6HNk6ab/CGw7FKRKWTmI8DyuCWgblzG8yx4sgr+A0Qsq6ly4wc1CJ+lqWxuC7x96bCJz5QJ6+hWgFtUX9OAXuesndxjfVNSKCJ2KoKIv+x82HrD7tX08QvbkVcL99wEvcMch+xwcD1Ub8nQehR2R1zu70FwEcoC3NzeEbCm1lwwlbozjPaYNuL+RKmiRAwcj5eX+ZwBhAA9XNOu2Rqkz5OdHqSirCu2l3gNwhC2szF9VvbImKAWlexcQJGV40NTLy99/ejcgzIP7eK+i1w7gEMHNkErhDDuDPpl8/KFe9y2RMzDKeyI3sp9Jo2psaRmwNiGQglSX+pElSAp57A0VLdhGvLQ0kvJklpL1Vawoo57V68If1GnaddyR3VwTXQze3VVZQzn3moDu2zvevpGXLgXI1yZVbNgtNVwL/F6KoMUB96xwBqA54BG1zyspQ8/xgoq/5nAEQzfEaCJ5SI5DIt62up1aR5qHIfRInfB4RAyL7jjsxtRcQbj51KQvGlD18/ZWPf3sntLWH4JNlDKti+mnEsLPKZ7OASHgiKzhKztHxSKLjf1CQ1gNaTdFtFJYxvWDsa8F5/8uuUrfFWS7HiiSgte/wbsiCFkYW7FDlLHJEUT3YPy30M5/wWjX3Xq5fkuNSpXb8Mw7BAPyJ/R6WbKVih54Qp7CjXOdCU2Y2hmGX8xGBxxM847OqHC2n1DhheINE3tTGlAstKkrkgKjYxwoK+TmGxCXnjPgJoLeWVVQ6/ZcMXjKKxxCDr8PKqfomvYEZiTMGyJzj69wG6uU33qi5Od8YesZzyrlfJgzf3fwA/FqWdfRaWGv9SSRTCKFhdvqr0s7E2BLjSAZpLlllgEzU9CdpWYg5K+Ks1oQBx3TMuLl+lmW/JhHrreJngjtbkLuOozWM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: acr-secret
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson

