apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: lms-static-canary
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: lms-static-canary
  policy:
    semver:
      range: '>=1.0.0'